openapi: 3.0.0
info:
  description: This is the API documentation for the Users endpoints of the Cartridge Web and Mobile Application.
  version: 1.0.0
  title: Cartridge - Users
  contact:
    email: Julianbir123@gmail.com

  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html

tags:
  - name: Users
    description: User profile and permission management endpoints

paths:
  /users/profile:
    get:
      security:
        - bearerAuth: []
      tags:
        - Users
      summary: Get user information on Cartridge Application
      operationId: showUser
      description: Get user information on Cartridge Application
      responses:
        '200':
          description: User Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Users'
        '404':
          description: Profile NOT Found

    put:
      security:
        - bearerAuth: []
      tags:
        - Users
      summary: Update user information on Cartridge Application
      operationId: editUser
      description: Update user information on Cartridge Application
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                email:
                  type: string
                profilePic:
                  type: string
                bio:
                  type: string
      responses:
        '200':
          description: User Updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Users'
        '404':
          description: User NOT Updated

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    Users:
      type: object
      properties:
        userId:
          type: integer
          example: 1234
        username:
          type: string
          example: "gamer"
        email:
          type: string
          example: "example@mail.com"
        profilePic:
          type: string
          format: uri
          example: "https://example.com"
        bio:
          type: string
          example: "I like to play games."
        isVerified:
          type: boolean
        createdAt:
          type: string
          format: date-time
          example: "2026-07-08T12:00:00Z"

servers:
  - url: http://www.cartridgeapp.fun
